# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: weixin-push-on-time

on:
  workflow_dispatch:
  schedule:
    # 每天9点-21点，每两个钟触发一次
    - cron: '*/5 * * * *'  # 每5分钟触发一次
    - cron: '0 1 * * *'  # 每天 UTC 时间 1点（CN 9点）
    - cron: '0 3 * * *'  # 每天 UTC 时间 3点（CN 11点）
    - cron: '0 5 * * *'  # 每天 UTC 时间 5点（CN 13点）
    - cron: '0 7 * * *'  # 每天 UTC 时间 7点（CN 15点）
    - cron: '0 9 * * *'  # 每天 UTC 时间 9点（CN 17点）
    - cron: '0 11 * * *' # 每天 UTC 时间 11点（CN 19点）
    - cron: '0 13 * * *' # 每天 UTC 时间 13点（CN 21点）
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # 添加定时任务指定运行分支 默认为master
    - uses: actions/checkout@v3
      with:
          ref: 'master'
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run dev --if-present
    env: 
      APP_ID: ${{secrets.APP_ID}}
      APP_SECRET: ${{secrets.APP_SECRET}}
      USER_INFO: ${{secrets.USER_INFO}}

